/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Event */
        post: operations["accept_event_api_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_v1_graph__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_v1_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/unsafe-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsafe Query */
        post: operations["unsafe_query_api_v1_demo_unsafe_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess */
        post: operations["assess_api_v1_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_api_v1_receipts__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Receipts */
        post: operations["verify_receipts_api_v1_receipts_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionCode
         * @enum {string}
         */
        ActionCode: "deny" | "delete" | "quarantine" | "tombstone" | "evict" | "suppress" | "rebuild" | "update_acl";
        /**
         * ActionState
         * @enum {string}
         */
        ActionState: "pending" | "leased" | "retryable" | "succeeded" | "failed" | "dead_letter";
        /** AssessmentFinding */
        AssessmentFinding: {
            /** Finding Id */
            finding_id: string;
            severity: components["schemas"]["AssessmentSeverity"];
            finding_class: components["schemas"]["FindingClass"];
            derivative_kind: components["schemas"]["ObjectKind"];
            /** Connector Ref */
            connector_ref: string;
            /** Target Version Id */
            target_version_id?: string | null;
            evidence_level: components["schemas"]["EvidenceLevel"];
            gap_code?: components["schemas"]["AssessmentGapCode"] | null;
            /** Confidence */
            confidence?: number | null;
            reason_code?: components["schemas"]["ReceiptReasonCode"] | null;
        };
        /**
         * AssessmentGapCode
         * @enum {string}
         */
        AssessmentGapCode: "missing_parent_edge" | "missing_policy_metadata" | "missing_lineage_metadata" | "unsupported_connector" | "unverified_semantic_candidate";
        /** AssessmentIncident */
        AssessmentIncident: {
            /** Incident Id */
            incident_id: string;
            severity: components["schemas"]["AssessmentSeverity"];
            /** Finding Ids */
            finding_ids: string[];
            reason_code: components["schemas"]["ReceiptReasonCode"];
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
        };
        /**
         * AssessmentSeverity
         * @enum {string}
         */
        AssessmentSeverity: "critical" | "high" | "medium" | "informational";
        /** ConnectorCapabilityVersion */
        ConnectorCapabilityVersion: {
            /** Connector Ref */
            connector_ref: string;
            /** Capability Version */
            capability_version: string;
            /** Supports Inventory */
            supports_inventory: boolean;
            /** Supports Mutation */
            supports_mutation: boolean;
            /** Supports Read Back */
            supports_read_back: boolean;
        };
        /** ConnectorFreshness */
        ConnectorFreshness: {
            /** Connector Ref */
            connector_ref: string;
            /** Store Ref */
            store_ref?: string | null;
            /** Capability Version */
            capability_version: string;
            /** Freshness Cursor */
            freshness_cursor: string;
            /** Reachable */
            reachable: boolean;
            /** Kinds */
            kinds?: components["schemas"]["ObjectKind"][];
        };
        /** CorrectionPayload */
        CorrectionPayload: {
            /** Replacement Version Id */
            replacement_version_id: string;
            /** Replacement Content Ref */
            replacement_content_ref: string;
            /** Replacement Fingerprint */
            replacement_fingerprint: string;
        };
        /** EventAccepted */
        EventAccepted: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            gate_state: components["schemas"]["LifecycleState"];
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "delete" | "correct" | "expire" | "permission_change";
        /**
         * EvidenceLevel
         * @enum {string}
         */
        EvidenceLevel: "L0" | "L1" | "L2" | "L3" | "L4";
        /** ExecutionReceipt */
        ExecutionReceipt: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /**
             * Receipt Version
             * @default 1
             * @constant
             */
            receipt_version: "1";
            /** Agent Id */
            agent_id: string;
            /** Key Id */
            key_id: string;
            /** Chain Sequence */
            chain_sequence: number;
            /** Previous Receipt Hash */
            previous_receipt_hash: string | null;
            /** Event Id */
            event_id: string;
            /** Run Id */
            run_id: string;
            /** Source Version Ids */
            source_version_ids: string[];
            /** Policy Version */
            policy_version: number;
            scope: components["schemas"]["ReceiptScope"];
            coverage_level: components["schemas"]["EvidenceLevel"];
            counts: components["schemas"]["ReceiptCounts"];
            /** Actions */
            actions: components["schemas"]["ReceiptAction"][];
            /** Verification Results */
            verification_results: components["schemas"]["ReceiptVerificationResult"][];
            /** Exclusions */
            exclusions: components["schemas"]["ReceiptExclusion"][];
            /** Unsupported Sinks */
            unsupported_sinks: components["schemas"]["UnsupportedSink"][];
            /** Residual Risks */
            residual_risks: components["schemas"]["ResidualRisk"][];
            outcome: components["schemas"]["RunOutcome"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Evidence Manifest Hash */
            evidence_manifest_hash: string;
            /**
             * Signature Algorithm
             * @default Ed25519
             * @constant
             */
            signature_algorithm: "Ed25519";
            /** Signature */
            signature: string;
        };
        /**
         * FindingClass
         * @enum {string}
         */
        FindingClass: "tracked" | "exact_untracked" | "semantic_candidate";
        /** GraphEdge */
        GraphEdge: {
            /** Parent Version Id */
            parent_version_id: string;
            /** Child Version Id */
            child_version_id: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Version Id */
            version_id: string;
            /** Object Id */
            object_id: string;
            kind: components["schemas"]["ObjectKind"];
            lifecycle_state: components["schemas"]["LifecycleState"];
        };
        /** GraphResponse */
        GraphResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /** Requested Version Id */
            requested_version_id: string;
            /** Root Version Ids */
            root_version_ids: string[];
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "failed";
            /** Checks */
            checks?: {
                [key: string]: "ok" | "degraded" | "failed";
            };
        };
        /** LifecycleEvent */
        LifecycleEvent: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Event Id */
            event_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Issuer Key Id */
            issuer_key_id: string;
            /** Audience */
            audience: string;
            /** Authority Ref */
            authority_ref: string;
            /** Nonce */
            nonce: string;
            /** Target Version Id */
            target_version_id: string;
            event_type: components["schemas"]["EventType"];
            /** Source Sequence */
            source_sequence: number;
            /** Policy Version */
            policy_version: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Effective At
             * Format: date-time
             */
            effective_at: string;
            /**
             * Command Expires At
             * Format: date-time
             */
            command_expires_at: string;
            /** Actor Ref */
            actor_ref: string;
            /** Reason Code */
            reason_code: string;
            correction?: components["schemas"]["CorrectionPayload"] | null;
            permission_change?: components["schemas"]["PermissionChangePayload"] | null;
        };
        /**
         * LifecycleState
         * @enum {string}
         */
        LifecycleState: "active" | "denied" | "tombstoned";
        /**
         * ObjectKind
         * @enum {string}
         */
        ObjectKind: "source" | "chunk" | "embedding" | "cache" | "summary" | "memory";
        /**
         * PermissionChangeKind
         * @enum {string}
         */
        PermissionChangeKind: "narrow" | "widen";
        /** PermissionChangePayload */
        PermissionChangePayload: {
            change: components["schemas"]["PermissionChangeKind"];
            /** New Acl Ref */
            new_acl_ref: string;
            /** New Policy Version */
            new_policy_version: number;
        };
        /** PostureAssessmentReport */
        PostureAssessmentReport: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: "1";
            /** Assessment Id */
            assessment_id: string;
            /** Scan Id */
            scan_id: string;
            /**
             * Read Only
             * @default true
             * @constant
             */
            read_only: true;
            coverage_level: components["schemas"]["EvidenceLevel"];
            /** Scope Manifest Hash */
            scope_manifest_hash: string;
            /** Denominators */
            denominators: {
                [key: string]: number;
            };
            /** Connector Freshness */
            connector_freshness: components["schemas"]["ConnectorFreshness"][];
            /** Findings */
            findings: components["schemas"]["AssessmentFinding"][];
            /** Lineage Gaps */
            lineage_gaps: components["schemas"]["AssessmentFinding"][];
            /** Unsupported Scope */
            unsupported_scope?: components["schemas"]["UnsupportedSink"][];
            /** Incidents */
            incidents: components["schemas"]["AssessmentIncident"][];
            /** Severity Counts */
            severity_counts: {
                [key: string]: number;
            };
            fixture_metrics?: components["schemas"]["ScannerFixtureMetrics"] | null;
            outcome: components["schemas"]["RunOutcome"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /** Purpose Ref */
            purpose_ref?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string | null;
            /** Supporting Version Ids */
            supporting_version_ids?: string[];
            /** Denied */
            denied: boolean;
            /** Reason Codes */
            reason_codes?: string[];
        };
        /** ReceiptAction */
        ReceiptAction: {
            /** Action Id */
            action_id: string;
            /** Target Version Ref */
            target_version_ref: string;
            derivative_kind: components["schemas"]["ObjectKind"];
            /** Connector Ref */
            connector_ref: string;
            action_code: components["schemas"]["ActionCode"];
            state: components["schemas"]["ActionState"];
            /** Attempt Count */
            attempt_count: number;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            reason_code?: components["schemas"]["ReceiptReasonCode"] | null;
        };
        /** ReceiptCounts */
        ReceiptCounts: {
            /** Expected Tracked */
            expected_tracked: number;
            /** Found Tracked */
            found_tracked: number;
            /** Scanner Candidates */
            scanner_candidates: number;
            /** Actions Attempted */
            actions_attempted: number;
            /** Actions Succeeded */
            actions_succeeded: number;
            /** Actions Failed */
            actions_failed: number;
            /** Targets Verified */
            targets_verified: number;
        };
        /** ReceiptExclusion */
        ReceiptExclusion: {
            /** Target Ref */
            target_ref?: string | null;
            /** Connector Ref */
            connector_ref?: string | null;
            derivative_kind?: components["schemas"]["ObjectKind"] | null;
            reason_code: components["schemas"]["ReceiptReasonCode"];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * ReceiptReasonCode
         * @enum {string}
         */
        ReceiptReasonCode: "declared_exclusion" | "connector_unreachable" | "connector_unsupported" | "store_mutation_failed" | "read_back_failed" | "policy_stale" | "legal_hold" | "outside_scope" | "scope_unknown" | "residual_payload" | "direct_store_bypass" | "unregistered_copy" | "host_trust";
        /** ReceiptScope */
        ReceiptScope: {
            /** Scope Manifest Hash */
            scope_manifest_hash: string;
            /** Scope Selected By */
            scope_selected_by: string;
            requested_evidence_level: components["schemas"]["EvidenceLevel"];
            /**
             * Scan Cutoff
             * Format: date-time
             */
            scan_cutoff: string;
            /** Registered Stores */
            registered_stores: number;
            /** Registered Connectors */
            registered_connectors: number;
            /** Reachable Connectors */
            reachable_connectors: number;
            /** Connector Capability Versions */
            connector_capability_versions: components["schemas"]["ConnectorCapabilityVersion"][];
            /** Unsupported Connectors */
            unsupported_connectors: string[];
            /** Graph Snapshot Hash */
            graph_snapshot_hash: string;
        };
        /** ReceiptVerificationResult */
        ReceiptVerificationResult: {
            /** Verification Id */
            verification_id: string;
            /** Target Version Ref */
            target_version_ref: string;
            /** Connector Ref */
            connector_ref: string;
            verification_code: components["schemas"]["VerificationCode"];
            result: components["schemas"]["VerificationStatus"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            reason_code?: components["schemas"]["ReceiptReasonCode"] | null;
        };
        /** ReceiptVerifyRequest */
        ReceiptVerifyRequest: {
            /** Receipts */
            receipts: components["schemas"]["ExecutionReceipt"][];
            /** Expected Sequence */
            expected_sequence: number;
            /** Expected Head */
            expected_head: string;
            /** Prior Trusted Head */
            prior_trusted_head?: string | null;
        };
        /** ReceiptVerifyResponse */
        ReceiptVerifyResponse: {
            /** Valid */
            valid: boolean;
            /** Verified Sequence */
            verified_sequence: number;
            /** Computed Head */
            computed_head?: string | null;
            /** Reason Codes */
            reason_codes?: string[];
        };
        /** ResidualRisk */
        ResidualRisk: {
            risk_code: components["schemas"]["ReceiptReasonCode"];
            /** Target Ref */
            target_ref?: string | null;
            /** Connector Ref */
            connector_ref?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * RunOutcome
         * @enum {string}
         */
        RunOutcome: "succeeded" | "partial" | "failed" | "unknown";
        /** RunStatusResponse */
        RunStatusResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /** Run Id */
            run_id: string;
            /** Event Id */
            event_id: string;
            /** Phase */
            phase: string;
            /** Counts */
            counts?: {
                [key: string]: number;
            };
            /** Failures */
            failures?: components["schemas"]["ReceiptAction"][];
            /** Exclusions */
            exclusions?: components["schemas"]["ReceiptExclusion"][];
            outcome?: components["schemas"]["RunOutcome"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ScanFinding */
        ScanFinding: {
            /** Finding Id */
            finding_id: string;
            finding_class: components["schemas"]["FindingClass"];
            derivative_kind: components["schemas"]["ObjectKind"];
            /** Connector Ref */
            connector_ref: string;
            /** Target Version Id */
            target_version_id?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /** Root Version Ids */
            root_version_ids?: string[];
        };
        /** ScanResponse */
        ScanResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Environment Id */
            environment_id: string;
            /** Scan Id */
            scan_id: string;
            /** Findings */
            findings: components["schemas"]["ScanFinding"][];
            /** Denominator */
            denominator: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** ScannerFixtureMetrics */
        ScannerFixtureMetrics: {
            /** Corpus Ref */
            corpus_ref: string;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /**
             * Fixture Only
             * @default true
             * @constant
             */
            fixture_only: true;
        };
        /** UnsupportedSink */
        UnsupportedSink: {
            /** Connector Ref */
            connector_ref: string;
            derivative_kind?: components["schemas"]["ObjectKind"] | null;
            /** Capability Version */
            capability_version?: string | null;
            /** @default connector_unsupported */
            reason_code: components["schemas"]["ReceiptReasonCode"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationCode
         * @enum {string}
         */
        VerificationCode: "payload_absent" | "tombstone_present" | "gate_denied" | "metadata_updated" | "branch_rebuilt" | "resurrection_blocked" | "store_read_back";
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "passed" | "failed" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    accept_event_api_v1_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-Lethe-Event-Signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifecycleEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_v1_graph__version_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_api_v1_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsafe_query_api_v1_demo_unsafe_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assess_api_v1_assessments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostureAssessmentReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_api_v1_receipts__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_receipts_api_v1_receipts_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
